### PR TITLE
Replicated embark demo template functionality using Vue.js

### PR DESCRIPTION
**Pull request by santteegt**
Creates an equivalent template of the react dapp generated by `embark demo` using Vue.js framework. This PR aims to solve opened issue in https://github.com/embark-framework/embark/issues/937

### CODE REVIEW

**Comment by jrainville** [comment]
Like I said in the other PR, this repo is meant to have a very simple Vue app. So we don't want to override what's in this repo.
Either find a solution to have both the demo and black app here or we'll have to put the demo app in the embark repo.

**Comment by santteegt** [comment]
Hi @jrainville,

What seems to be a good alternative is to push the demo source code under a different branch e.g. `demo`. Then I just have to append the placeholder `#demo` to the git URL, and embark downloads the code from the specified branch. I've tested this approach and it worked!

Let me know if that works for you.

**Comment by jrainville** [comment]
Sounds like a good idea, what do you think @iurimatias ?

**Comment by santteegt** [comment]
Hi,

If you agree on the idea to manage this demo source code on a `demo` branch instead of copying it into the embark `templates` repo dir, could you please create it in order to make a new PR that supersedes this one?

**Comment by 0x-r4bbit** [comment]
Hi, I've created a `demo` branch which happily awaits your PR. Maybe it's possible to just change the base branch of this PR.

**Pull request merged**
